# Generated by Django 4.2.20 on 2025-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # No operations - this is an empty migration
    ] 