# Generated by Django 4.2.21 on 2025-05-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter your text here (minimum 15 characters)')),
                ('classification', models.CharField(choices=[('diary', 'Diary')], default='diary', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Entry',
                'verbose_name_plural': 'Manual Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
