# Generated by Django 4.2.20 on 2025-05-04 12:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('delete_after_download', models.BooleanField(default=False)),
                ('add_timestamp', models.BooleanField(default=True)),
                ('timestamp_format', models.CharField(default='%Y%m%d_%H%M%S_%f', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Drive Configuration',
                'verbose_name_plural': 'Global Drive Configuration',
            },
        ),
        migrations.CreateModel(
            name='UserDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_folders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('download_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Drive Configuration',
                'verbose_name_plural': 'User Drive Configurations',
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=100)),
                ('source_folder', models.CharField(max_length=255)),
                ('local_path', models.CharField(max_length=500)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_from_drive', models.BooleanField(default=False)),
                ('file_size', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
