# Generated by Django 4.2.20 on 2025-05-06 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('download_gdrive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='whisper-1', max_length=100)),
                ('response_format', models.CharField(choices=[('json', 'JSON'), ('text', 'Plain Text'), ('srt', 'SRT'), ('vtt', 'VTT')], default='json', max_length=20)),
                ('cost_management', models.JSONField(blank=True, default=dict, help_text='Settings for maximum duration and other cost controls')),
                ('default_prompt', models.TextField(blank=True, help_text='System-wide default prompt for transcription', null=True)),
                ('timestamp_format', models.CharField(default='%Y%m%d_%H%M%S_%f', help_text='Format for timestamping transcription files', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Transcription Configuration',
                'verbose_name_plural': 'Global Transcription Configuration',
            },
        ),
        migrations.CreateModel(
            name='UserTranscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text="User's OpenAI API key (stored securely)", max_length=255)),
                ('language', models.CharField(blank=True, help_text="Preferred language code (e.g., 'en', 'fr', 'es')", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Transcription Configuration',
                'verbose_name_plural': 'User Transcription Configurations',
            },
        ),
    ]
