# Generated by Django 4.2.20 on 2025-05-06 16:48

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('download_gdrive', '0002_transcriptionglobalconfig_usertranscriptionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertranscriptionconfig',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(help_text="User's OpenAI API key (stored encrypted)", max_length=255)),
        ),
    ]
