# Generated by Django 4.2.20 on 2025-05-07 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('download_gdrive', '0003_alter_usertranscriptionconfig_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(help_text='Google Drive file ID', max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('model', models.CharField(default='gpt-4o-transcribe', max_length=100)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('result_path', models.CharField(blank=True, max_length=500, null=True)),
                ('result_format', models.CharField(default='json', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('download_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_jobs', to='download_gdrive.downloadrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transcription Job',
                'verbose_name_plural': 'Transcription Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
