# Generated by Django 4.2.21 on 2025-05-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_gdrive', '0004_transcriptionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='transcript_content',
            field=models.TextField(blank=True, help_text='Full transcription content', null=True),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='transcript_summary',
            field=models.TextField(blank=True, help_text='Short summary of the transcription', null=True),
        ),
    ]
