# Generated by Django 4.2.21 on 2025-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_gdrive', '0005_transcriptionjob_transcript_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='content_label',
            field=models.CharField(choices=[('unlabeled', 'Unlabeled'), ('diary', 'Diary'), ('calendar', 'Calendar'), ('meeting', 'Meeting'), ('note', 'Note'), ('todo', 'Todo'), ('other', 'Other')], default='unlabeled', help_text='Content category label (diary, calendar, etc.)', max_length=30),
        ),
    ]
