# Generated by Django 4.2.21 on 2025-05-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Contact's full name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Contact's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Contact's phone number", max_length=20)),
                ('address', models.TextField(blank=True, help_text="Contact's physical address")),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the contact')),
                ('category', models.CharField(blank=True, help_text='Optional category for organizing contacts', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
    ]
