# Generated by Django 4.2.21 on 2025-05-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="Contact's first name", max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text="Contact's last name", max_length=100)),
                ('alias', models.CharField(blank=True, help_text='Nickname or alternative name', max_length=100)),
                ('nickname', models.CharField(blank=True, help_text="Contact's nickname", max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Main email address', max_length=254)),
                ('private_email', models.EmailField(blank=True, help_text='Private/personal email address', max_length=254)),
                ('professional_email', models.EmailField(blank=True, help_text='Work/professional email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Main phone number', max_length=20)),
                ('private_phone', models.CharField(blank=True, help_text='Private/mobile phone number', max_length=20)),
                ('professional_phone', models.CharField(blank=True, help_text='Work/professional phone number', max_length=20)),
                ('mobile', models.CharField(blank=True, help_text="Contact's mobile number", max_length=20)),
                ('address', models.TextField(blank=True, help_text="Contact's physical address")),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the contact')),
                ('category', models.CharField(blank=True, help_text='Optional category for organizing contacts', max_length=50)),
                ('company', models.CharField(blank=True, help_text="Contact's company or organization", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text="Contact's job title or position", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
